name: mille-text # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '5.7.15' # just for humans, typically '1.2+git' or '1.3.2'
summary: Classic text-based version of the card game Mille Bournes
description: |
  Classic text-based version of the card game Mille Bournes

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mille_icon.png
title: Mille Bournes (Text)

apps:
  millebournes:
    command: millebournes
parts:
  millebournes:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      millebournes: build/
      millebournes.1: man/man1/

architectures:
  - build-on: amd64

